#!/bin/bash

SERVICES="ssh nginx"

function start {
    for service in $SERVICES
    do
        echo "Launch $service ..."
        if [ $service == nginx ]
        then
            check_nginx
        fi
        service $service start
    done
}

function config_prov {
    DIRD_CONF_NAME=${DIRD_CONF_NAME:-"xivo-dird.yml"}

    if [ ! -z $DIRD_URL ]
    then
        echo "Provisioning config file from $DIRD_URL"
        curl -s $DIRD_URL/$DIRD_CONF_NAME -o /etc/xivo/xivo-dird/xivo-dird.yml
    fi

    if [ ! -z $DIRD_PLUGINS ]
    then
        for P in $DIRD_PLUGINS
            echo "Download $P plugin config"
            curl -s $DIRD_URL/$P -o /etc/xivo/xivo-dird/plugins.d/$P
    fi
}

function check_nginx {
    service nginx status
    if [ $? == 0 ]
    then
        pkill -9 nginx
    fi
}

# Launching xivo-dird
start
config_prov
xivo-dird -d -f -u www-data
